### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ayedo** [pubref/rules_kotlin#23]
Hi!

First of all: thanks for your great work :) 

I've tried creating a project according to the documentation, but I cannot run the resulting jar file. It prints:

`Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at test.MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more`

Here is a minimal project I'm trying to run: [RulesKotlinMinimal.zip](https://github.com/pubref/rules_kotlin/files/1066420/RulesKotlinMinimal.zip)

UPDATE This fixed my problem: https://github.com/plumpy/rules_kotlin/commit/54158aa6ee0d4fd1a07867a72c721316511fe05b

**Comment by pcj** [comment]
Closed by #25.
